package UI;

/**
 *
 * @author MarkC
 */
public class DialogBox extends javax.swing.JFrame {

    /**
     * Creates new form DialogBox
     */
    public DialogBox() {
        initComponents();
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        credentials_root_pane = new keeptoo.KGradientPanel();
        credentials_label = new javax.swing.JLabel();
        website_textfield = new javax.swing.JTextField();
        website_lbl = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        username_lbl = new javax.swing.JLabel();
        password_textfield = new javax.swing.JTextField();
        password_lbl = new javax.swing.JLabel();
        displayCredentials_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        credentials_root_pane.setkEndColor(new java.awt.Color(176, 106, 179));
        credentials_root_pane.setkGradientFocus(850);
        credentials_root_pane.setkStartColor(new java.awt.Color(69, 104, 220));

        credentials_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        credentials_label.setForeground(new java.awt.Color(204, 204, 204));
        credentials_label.setText("Credentials");

        website_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                website_textfieldActionPerformed(evt);
            }
        });

        website_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        website_lbl.setForeground(new java.awt.Color(204, 204, 204));
        website_lbl.setText("Website:");

        username_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_lbl.setForeground(new java.awt.Color(204, 204, 204));
        username_lbl.setText("Username");

        password_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_lbl.setForeground(new java.awt.Color(204, 204, 204));
        password_lbl.setText("Password:");

        displayCredentials_btn.setText("Display Credentials");
        displayCredentials_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCredentials_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout credentials_root_paneLayout = new javax.swing.GroupLayout(credentials_root_pane);
        credentials_root_pane.setLayout(credentials_root_paneLayout);
        credentials_root_paneLayout.setHorizontalGroup(
            credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentials_root_paneLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_lbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentials_root_paneLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(credentials_label)
                        .addGap(124, 124, 124))
                    .addGroup(credentials_root_paneLayout.createSequentialGroup()
                        .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_lbl)
                            .addComponent(website_lbl))
                        .addGap(27, 27, 27)
                        .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayCredentials_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(username_textfield)
                                .addComponent(website_textfield))))))
        );
        credentials_root_paneLayout.setVerticalGroup(
            credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credentials_root_paneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(credentials_label)
                .addGap(26, 26, 26)
                .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(website_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(website_lbl))
                .addGap(27, 27, 27)
                .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_lbl))
                .addGap(31, 31, 31)
                .addGroup(credentials_root_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_lbl))
                .addGap(45, 45, 45)
                .addComponent(displayCredentials_btn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credentials_root_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(credentials_root_pane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayCredentials_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCredentials_btnActionPerformed
        String finalStringPass = new String(myGUI_1.getFinalPasswordByteArray());
        password_textfield.setText(finalStringPass);
        website_textfield.setText(myGUI_1.getFinalURL());
        username_textfield.setText(myGUI_1.getFinalUser());
    }//GEN-LAST:event_displayCredentials_btnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                password_textfield.setText("");
        website_textfield.setText("");
        username_textfield.setText("");
    }//GEN-LAST:event_formWindowClosing

    private void website_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_website_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_website_textfieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel credentials_label;
    private keeptoo.KGradientPanel credentials_root_pane;
    private javax.swing.JButton displayCredentials_btn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_textfield;
    private javax.swing.JLabel website_lbl;
    private javax.swing.JTextField website_textfield;
    // End of variables declaration//GEN-END:variables
}
